### ISSUE TITLE
Add Twitter integration

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-social-tipbot#3]
Would be awesome to have a tipbot on twitter - maybe we can leverage one of the other open source ones.

**Comment by filipnyquist** [comment]
We now have a tipbot on twitter, closing this one.

**Comment by kauffj** [comment]
Is this tip bot just reddit then? If so, can it be renamed?

Is there an ability (and value) in some of the various tip bots sharing code and/or a data backend?

**Comment by tzarebczan** [comment]
Twitter tipbot is under: https://github.com/lbryio/twitter-tipbot

In the future we can possibly add FB or other social tipping to this tipbot, so we can leave the name as such.

Internal issue to consolidate: https://github.com/lbryio/internal-issues/issues/126
